version: "3.7"

networks:
  spendmanagement:
    external:
      name: spendmanagement-network

services:

    identity:
      container_name: spendmanagement_identity
      build:
        context: .
        dockerfile: Dockerfile
      image: spendmanagement_identity
      
      ports:
        - 9515:8080
      networks:
        - spendmanagement