version: "3.7"

networks:
  spendmanagement:
    external:
      name: spendmanagement-network

services:

    identity:
      container_name: spendmanagement_identity
      build:
        context: .
        dockerfile: Dockerfile
      image: spendmanagement_identity:${APP_VERSION}
      environment:
        - APP_VERSION=${APP_VERSION}
      ports:
        - 8082:8080
      networks:
        - spendmanagement