name: Bump build version on PR to master

on:
  pull_request:
    branches:
      - main

jobs:
  print_commit_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Commit Message
        run: echo "$(git log -1 --pretty=%B)"
