name: Bump build version

on:
  push:
    branches: [ main ]

jobs:
  print_commit_message:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir Mensagem de Commit
        run: echo "${{ github.event.workflow_run.head_commit.message }}"
