name: build_and_run_tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION_UPDATE_TYPE: "value"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Identity.Api/Identity.Api.csproj
    - name: Build
      run: dotnet build --no-restore --configuration Release src/Identity.Api/Identity.Api.csproj

  unit-tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies for unit tests
        run: dotnet restore tests/Identity.UnitTests/Identity.UnitTests.csproj
      - name: Build project
        run: dotnet build --no-restore --configuration Release tests/Identity.UnitTests/Identity.UnitTests.csproj
      - name: Run unit tests
        run: dotnet test --verbosity normal tests/Identity.UnitTests/Identity.UnitTests.csproj

  integration-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - name: Setup PostgreSQL
        run: |
          docker run -d --name postgres -p 5432:5432 \
            -e POSTGRES_PASSWORD=postgres \
            --health-cmd pg_isready \
            --health-interval 10s \
            --health-timeout 5s \
            --health-retries 5 \
            postgres
  
      - name: Wait for PostgreSQL to start
        run: |
          until docker exec postgres pg_isready; do
            sleep 1;
          done

      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run integration tests
        run: |
          dotnet restore tests/Identity.IntegrationTests/Identity.IntegrationTests.csproj
          dotnet build --no-restore --configuration Release tests/Identity.IntegrationTests/Identity.IntegrationTests.csproj
          dotnet test --verbosity normal tests/Identity.IntegrationTests/Identity.IntegrationTests.csproj      



