name: Bump build version

on:
  push:
    branches: [main]

jobs:
  print_commit_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Commit Message
        run: echo "${{ github.event.head_commit.message }}"
