name: Bump build version on PR to master

on:
  pull_request:
    branches:
      - master

jobs:
  print_commit_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Commit Message
        run: echo "${{ github.event.pull_request.head.sha }}"
